import type { Metadata } from "next";
import "./globals.scss";
import CookieBanner from "@/components/CookieBanner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="govuk-template__body">
        <CookieBanner />
        <main className="govuk-width-container govuk-main-wrapper" id="main-content">
          {children}
        </main>
      </body>
    </html>
  );
}
